
name: Build Padawan

on:
   push:
    branches: [ hc5861 ]
         
#  schedule:
#    - cron: 0 8 * * 5
#  watch:
#    types: started

env:
  REPO_URL: https://github.com/lzf213/Padavan.git
  REPO_BRANCH: hc5861
  CONFIG_FILE: .config
  DIY_SH: diy.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -qy 
        sudo apt-get -qy unzip libtool curl cmake gperf gawk flex bison nano \
                git python-docutils gettext automake autopoint texinfo build-essential fakeroot \
                pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev
    
        sudo apt autoremove -y
        sudo apt autoclean  -y
        
    - name: Clone source code
      run: git clone --depth=1 $REPO_URL /opt/rt-n56u

    - name: Build toolchain-mipsel
      run: |
        cd /opt/rt-n56u/toolchain-mipsel
        sudo ./clean_sources
        sudo ./build_toolchain

    - name: Build_firmware
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clean_sources
        sudo ./build_firmware
 
     
    - name: Upload firmware
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: hc5861.trx
        path: /opt/rt-n56u/trunk/images
